// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YggdrasilApi.Data;

#nullable disable

namespace YggdrasilApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("YggdrasilApi.Models.Connection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FromNodeId")
                        .HasColumnType("int");

                    b.Property<int>("FromPortId")
                        .HasColumnType("int");

                    b.Property<int?>("GraphId")
                        .HasColumnType("int");

                    b.Property<int>("ToNodeId")
                        .HasColumnType("int");

                    b.Property<int>("ToPortId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GraphId");

                    b.ToTable("Connections");
                });

            modelBuilder.Entity("YggdrasilApi.Models.Decleration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TemplateId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.ToTable("Declerations");
                });

            modelBuilder.Entity("YggdrasilApi.Models.Graph", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TemplateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.ToTable("Graphs");
                });

            modelBuilder.Entity("YggdrasilApi.Models.Node", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("GraphId")
                        .HasColumnType("int");

                    b.Property<int>("PositionX")
                        .HasColumnType("int");

                    b.Property<int>("PositionY")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GraphId");

                    b.ToTable("Nodes");
                });

            modelBuilder.Entity("YggdrasilApi.Models.Template", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.PrimitiveCollection<string>("Derives")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Templates");
                });

            modelBuilder.Entity("YggdrasilApi.Models.Connection", b =>
                {
                    b.HasOne("YggdrasilApi.Models.Graph", null)
                        .WithMany("Connections")
                        .HasForeignKey("GraphId");
                });

            modelBuilder.Entity("YggdrasilApi.Models.Decleration", b =>
                {
                    b.HasOne("YggdrasilApi.Models.Template", null)
                        .WithMany("Declerations")
                        .HasForeignKey("TemplateId");
                });

            modelBuilder.Entity("YggdrasilApi.Models.Graph", b =>
                {
                    b.HasOne("YggdrasilApi.Models.Template", null)
                        .WithMany("Graphs")
                        .HasForeignKey("TemplateId");
                });

            modelBuilder.Entity("YggdrasilApi.Models.Node", b =>
                {
                    b.HasOne("YggdrasilApi.Models.Graph", null)
                        .WithMany("Nodes")
                        .HasForeignKey("GraphId");
                });

            modelBuilder.Entity("YggdrasilApi.Models.Graph", b =>
                {
                    b.Navigation("Connections");

                    b.Navigation("Nodes");
                });

            modelBuilder.Entity("YggdrasilApi.Models.Template", b =>
                {
                    b.Navigation("Declerations");

                    b.Navigation("Graphs");
                });
#pragma warning restore 612, 618
        }
    }
}
